### PR TITLE
Pfizer

### PR DESCRIPTION
**Pull request by KageyamaJie**

### CODE REVIEW

**Comment by KageyamaJie** [comment]
Group created

**Comment by KageyamaJie** [comment]
So what is the task for this Pfizer Project?

**Comment by KageyamaJie** [comment]
@ckming94 @ManfredOoi @WongKaiSung

**Comment by ManfredOoi** [comment]
We want to create the system to 2 modules, maintain employee and product module and sales module for staff

**Comment by KageyamaJie** [comment]
2 modules as to the Staff and Product (sales)? All CRUD will be included?

**Comment by WongKaiSung** [comment]
@ManfredOoi which part i handle?

**Comment by ManfredOoi** [comment]
The leader will decide @WongKaiSung Leader: ( @ckming94 )

**Comment by ckming94** [comment]
I agree on taking out DELETE function, since we should not delete those primary key records.

**Comment by KageyamaJie** [comment]
Since the delete function will be taken out and replace it with updating the status. What else? Since the Staff module can be managed by CRUD (except the delete function). While the Product module will consist of all the item's details as well as the price and also remove function will be excluded. Generate receipt will be needed?

**Comment by ManfredOoi** [comment]
The generate receipt is a must function for Pfizer

**Comment by ckming94** [comment]
Besides that, I think that we need a subsystem that responsible for purchase check out and calculating the total payment.

**Comment by ckming94** [comment]
Generate receipt will be like what we have done before for other system. It will show all the needed purchased details.

**Comment by KageyamaJie** [comment]
Besides generate receipt and retrieve purchased details. What else will be included?

**Comment by WongKaiSung** [comment]
how about the login function?

**Comment by KageyamaJie** [comment]
I suppose it will be required?

**Comment by WongKaiSung** [comment]
Of course, so we have to add this into the backlog in pivotaltracker.

**Comment by ckming94** [comment]
Guys, lets me summary all the module that we need.
Pfizer Pharmacy System:-
- Login module
- Staff module
- Product module
- Sales module
These will be the needed modules for now.
Lets put it into our backlog.

**Comment by ManfredOoi** [comment]
Okay, noted

**Comment by KageyamaJie** [comment]
Alright.

**Comment by WongKaiSung** [comment]
Okay.

**Comment by ManfredOoi** [comment]
The staff module, I think we change it to Employee profile module much better. How about you all think? keep it or any better suggestion to give?

**Comment by ckming94** [comment]
both also acceptable,

**Comment by ManfredOoi** [comment]
So i will be in-charge of Sales Module and the update employee profile, so I almost complete the update employee profile, how are you guys doing? Any obstacle confronting?

**Comment by ManfredOoi** [comment]
I have completed the update employee function, now i will proceed to Sales module

**Comment by WongKaiSung** [comment]
Guys, I have completed the login module.

**Comment by ManfredOoi** [comment]
So far I m dealing with dynamic button generate, which a new product is created, then in the sales modules there will be  a button generate in the sales module

**Comment by ManfredOoi** [comment]
Any idea or solution to provide?

**Comment by ckming94** [comment]
using dynamic button  must retrieve the number of the record in the particular category, once you know the number of record return the number and by using the number of quantity to decide how many rows needed in the grid layout. Take note that we should decide how many column first such as 4 column each row, then we are only have to increase the row to make sure all the record can be represent in a button in the column.

**Comment by ckming94** [comment]
besides that, you are also required to return each record as well to code it into a button.

**Comment by ManfredOoi** [comment]
okay according to the solution you described, I finally made a dynamic button on the sales module.

**Comment by ManfredOoi** [comment]
Any way, should I include the tax calculation as well?

**Comment by WongKaiSung** [comment]
Yes. It will be better if you follow the country tax regulations since Pfizer is a large local pharmacy that should follow the tax regulations defined by Malaysia government.

**Comment by KageyamaJie** [comment]
The staff module is progressing smoothly. Which includes the necessary functions for the program as well.

**Comment by ManfredOoi** [comment]
Alright guys, what is the discount rate for non-member, membership, VIP offered by Pfizer?

**Comment by ckming94** [comment]
The system shall not be giving any discount to non-member. There should be a 10% discount for member and there are no VIP in the business.

**Comment by ManfredOoi** [comment]
Okay, noted, let me get into conclusion, we have 2 categories of customer which are non-membership and membership. So anyone have some comment about it?

**Pull request merged**
